name = "payrune-api"
main = "src/index.mjs"
compatibility_date = "2026-03-10"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[observability]
enabled = true

[observability.logs]
invocation_logs = true
head_sampling_rate = 1

[vars]
BITCOIN_MAINNET_REQUIRED_CONFIRMATIONS = "2"
BITCOIN_TESTNET4_REQUIRED_CONFIRMATIONS = "2"
BITCOIN_MAINNET_RECEIPT_EXPIRES_AFTER = "24h"
BITCOIN_TESTNET4_RECEIPT_EXPIRES_AFTER = "24h"
