services:
  app:
    environment:
      BITCOIN_MAINNET_LEGACY_XPUB: ${BITCOIN_MAINNET_LEGACY_XPUB:-}
      BITCOIN_MAINNET_SEGWIT_XPUB: ${BITCOIN_MAINNET_SEGWIT_XPUB:-}
      BITCOIN_MAINNET_NATIVE_SEGWIT_XPUB: ${BITCOIN_MAINNET_NATIVE_SEGWIT_XPUB:-}
      BITCOIN_MAINNET_TAPROOT_XPUB: ${BITCOIN_MAINNET_TAPROOT_XPUB:-}
