services:
  app:
    environment:
      BITCOIN_TESTNET4_LEGACY_XPUB: ${BITCOIN_TESTNET4_LEGACY_XPUB:-}
      BITCOIN_TESTNET4_SEGWIT_XPUB: ${BITCOIN_TESTNET4_SEGWIT_XPUB:-}
      BITCOIN_TESTNET4_NATIVE_SEGWIT_XPUB: ${BITCOIN_TESTNET4_NATIVE_SEGWIT_XPUB:-}
      BITCOIN_TESTNET4_TAPROOT_XPUB: ${BITCOIN_TESTNET4_TAPROOT_XPUB:-}
